// Tool manifest. Metadata lives here so the navigation renders without loading any tool; each tool's code is fetched on demand
// (opening Base64 used to download every tool: 46 requests, 102 KB). tests/js/manifest.test.mjs fails if a tool's own
// metadata drifts from this list. A tool module is { id, title, group, blurb, keywords, needsAuth, mount(root, ctx) }.
export const GROUPS = ["Links", "QR & URLs", "Encode & decode", "Generate", "Format & convert", "Images", "Network & web", "Admin"];

// `load` is a literal `() => import("./x.js")` on purpose: bundlers (see scripts/bundle.mjs) can only follow static import paths.
const entry = (load, id, title, group, blurb, keywords = "", needsAuth = false) =>
  ({ id, title, group, blurb, keywords, needsAuth, load: () => load().then(m => m.default) });

export const tools = [
  entry(() => import("./links.js"), "links", "Short links", "Links",
    "Create, search, edit and track short links.",
    "url shortener shorten link redirect", true),
  entry(() => import("./bulk.js"), "bulk", "Bulk shorten", "Links",
    "Shorten a whole list at once: one URL per line, optionally followed by a space and a custom slug. Up to 500 per run.",
    "many urls list batch shorten csv", true),
  entry(() => import("./qr.js"), "qr", "QR code generator", "QR & URLs",
    "Make QR codes for links, Wi-Fi, contacts, email, SMS and locations. Generated in your browser: Wi-Fi passwords and contact details never leave this page.",
    "qr wifi vcard barcode scan", false),
  entry(() => import("./tracer.js"), "tracer", "Redirect tracer", "QR & URLs",
    "See where a link really goes before you click it: every redirect hop, the final page's title and the HTTP status. Fetched by your Hitchly server, which refuses internal addresses.",
    "unshorten expand redirect chain where does this link go preview title", true),
  entry(() => import("./utm.js"), "utm", "UTM builder", "QR & URLs",
    "Add campaign parameters to a URL. Existing query strings and #fragments are kept. Shorten the result with one click.",
    "campaign tracking google analytics link tagging", false),
  entry(() => import("./urlparse.js"), "url-parser", "URL parser & cleaner", "QR & URLs",
    "Take a URL apart, and strip tracking parameters (utm_*, fbclid, gclid, …) before you share or shorten it.",
    "query parameters tracking fbclid utm strip clean", false),
  entry(() => import("./base64.js"), "base64", "Base64", "Encode & decode",
    "Encode text to Base64 or decode it back. UTF-8 safe; accepts URL-safe input and missing padding.",
    "encode decode binary base64url", false),
  entry(() => import("./urlcodec.js"), "url-encode", "URL encode / decode", "Encode & decode",
    "Percent-encode or decode text for use in URLs and query strings.",
    "percent encoding uri query string", false),
  entry(() => import("./escape.js"), "escape", "Escape & unescape", "Encode & decode",
    "Escape text for HTML, JavaScript or JSON strings and SQL literals, or turn escaped text back into plain text.",
    "html entities javascript json sql quotes backslash", false),
  entry(() => import("./textenc.js"), "textenc", "Text ⇄ bytes, Unicode & NATO", "Encode & decode",
    "See text as UTF-8 bytes in binary, octal, decimal or hex (and back), inspect every Unicode code point, or spell text with the NATO phonetic alphabet.",
    "binary hex octal decimal utf-8 utf-16 code point unicode phonetic alphabet", false),
  entry(() => import("./jwt.js"), "jwt", "JWT decoder", "Encode & decode",
    "Read a token's header and claims. It decodes only: the signature is NOT verified, so never treat the result as proof of who sent it. Runs entirely in your browser.",
    "json web token bearer claims", false),
  entry(() => import("./hash.js"), "hash", "Hash & HMAC", "Encode & decode",
    "SHA-1/256/384/512 of text or a file, plus HMAC. Computed locally with the browser's crypto; nothing is uploaded. (MD5 is not offered: it is broken for security use.)",
    "sha256 sha1 sha512 checksum hmac digest file", false),
  entry(() => import("./encrypt.js"), "encrypt", "Encrypt & decrypt text", "Encode & decode",
    "Encrypt a message with a passphrase (PBKDF2-SHA256 → AES-256-GCM) and get a text token you can paste anywhere; decrypt it again with the same passphrase. A weak passphrase is still weak, and this is for short notes, not a substitute for dedicated file-encryption software.",
    "aes gcm pbkdf2 passphrase password secret encrypt decrypt", false),
  entry(() => import("./uuid.js"), "uuid", "UUID & ULID generator", "Generate",
    "Generate random v4 UUIDs, time-ordered v7 UUIDs or ULIDs (both sort by creation time, good database keys), and inspect an existing identifier.",
    "guid v4 v7 ulid identifier random sortable", false),
  entry(() => import("./password.js"), "password", "Password & token generator", "Generate",
    "Cryptographically random passwords and tokens, generated in your browser with unbiased sampling. Nothing is sent or stored.",
    "random secret api key strong", false),
  entry(() => import("./totp.js"), "totp", "TOTP (2FA) codes", "Generate",
    "Generate the six-digit code an authenticator app would show for a secret, create a new secret with its QR code, and check a code. Everything happens in your browser; still avoid pasting a production secret on a computer you don't trust.",
    "otp authenticator google authenticator 2fa two factor rfc 6238 hotp", false),
  entry(() => import("./keys.js"), "keys", "RSA / ECDSA / Ed25519 key pairs", "Generate",
    "Generate a key pair in your browser and download it as PEM (PKCS#8 private, SPKI public). Handy for tests and demos; for production keys prefer your own trusted tooling and never paste a private key into a site you don't control.",
    "pem public private key ssh rsa ecdsa ed25519 fingerprint pkcs8 spki", false),
  entry(() => import("./lorem.js"), "lorem", "Lorem ipsum generator", "Generate",
    "Placeholder text by the word, sentence or paragraph.",
    "placeholder text dummy filler paragraphs", false),
  entry(() => import("./json.js"), "json", "JSON formatter", "Format & convert",
    "Validate, pretty-print or minify JSON, with line and column for errors.",
    "pretty print minify validate sort keys", false),
  entry(() => import("./convert.js"), "convert", "JSON · YAML · XML · CSV converter", "Format & convert",
    "Convert between JSON, YAML, XML and CSV in your browser. YAML is read as a documented subset (no anchors, tags or multi-document files) and unsupported input is reported, never guessed.",
    "convert transform yaml to json xml csv", false),
  entry(() => import("./diff.js"), "diff", "Text & JSON diff", "Format & convert",
    "See exactly what changed between two texts, by line, word or character, or compare two JSON documents structurally (key order is ignored).",
    "compare difference changes patch unified", false),
  entry(() => import("./cron.js"), "cron", "Cron explainer", "Format & convert",
    "Paste a five-field cron expression to get a plain-English description and its next run times. Supports lists, ranges, steps, month/day names and @daily-style macros.",
    "crontab schedule job expression next run", false),
  entry(() => import("./time.js"), "time", "Timestamp converter", "Format & convert",
    "Convert between Unix time (seconds or milliseconds, auto-detected), ISO dates and time zones.",
    "unix epoch date timezone iso", false),
  entry(() => import("./color.js"), "color", "Color converter & contrast", "Format & convert",
    "Convert HEX / RGB / HSL and check WCAG contrast between a text and a background colour.",
    "hex rgb hsl wcag accessibility", false),
  entry(() => import("./regex.js"), "regex", "Regex tester", "Format & convert",
    "Test a JavaScript regular expression against text. Matches, capture groups and named groups are listed; runaway patterns are stopped.",
    "regular expression match groups javascript", false),
  entry(() => import("./text.js"), "text", "Text utilities", "Format & convert",
    "Change case, make a URL slug, and count words, characters and reading time.",
    "case camel snake kebab slug word count characters", false),
  entry(() => import("./radix.js"), "radix", "Number base converter", "Format & convert",
    "Convert integers between binary, octal, decimal, hexadecimal and base 36. Arbitrarily large numbers are exact.",
    "binary hex octal decimal base36 bigint", false),
  entry(() => import("./units.js"), "units", "Unit, percentage & Roman numeral converters", "Format & convert",
    "Everyday conversions: length, mass, temperature, data sizes (KB vs KiB), time, percentages and Roman numerals.",
    "convert length weight temperature celsius fahrenheit bytes percent roman", false),
  entry(() => import("./chmod.js"), "chmod", "chmod calculator", "Format & convert",
    "Tick permissions or type the octal (755) or symbolic (rwxr-xr-x) form; all three stay in sync.",
    "unix file permissions octal 755 644 rwx setuid sticky", false),
  entry(() => import("./validate.js"), "validate", "IBAN validator & email normaliser", "Format & convert",
    "Check an IBAN's country length and checksum, or reduce email addresses to a canonical form for de-duplication. Nothing is looked up or sent anywhere.",
    "iban bank account checksum email normalize gmail dots plus tag duplicate", false),
  entry(() => import("./imgmeta.js"), "image-privacy", "Photo privacy cleaner", "Images",
    "See what a photo gives away (camera, date, GPS location) and remove it without re-encoding: the picture itself stays byte-for-byte identical. Nothing is uploaded.",
    "exif gps location metadata remove strip photo privacy jpeg png webp", false),
  entry(() => import("./imgconvert.js"), "image-convert", "Image converter & compressor", "Images",
    "Convert between PNG, JPEG and WebP, resize and compress. Runs in your browser; the image is never uploaded. Re-encoding drops metadata as a side effect.",
    "resize compress shrink convert png jpeg jpg webp scale reduce size photo", false),
  entry(() => import("./favicon.js"), "favicon", "Favicon & app icon generator", "Images",
    "Turn one image into favicon.ico, Apple touch icon and PWA icons, plus the HTML and manifest to use them, in a single ZIP. Built in your browser.",
    "favicon ico apple touch icon pwa manifest 192 512 app icon png", false),
  entry(() => import("./colorblind.js"), "colour-blindness", "Colour-blindness simulator", "Images",
    "See an image or screenshot the way people with the common colour-vision deficiencies see it. An approximation (Machado 2009), not a medical test. Runs in your browser.",
    "colorblind color blind accessibility protanopia deuteranopia tritanopia a11y vision", false),
  entry(() => import("./datauri.js"), "data-uri", "File ⇄ data: URI", "Images",
    "Turn a small file into a data: URI to inline in HTML or CSS, or paste a data: URI to preview and download it. Base64 adds about a third to the size.",
    "data uri base64 embed inline image css html convert decode", false),
  entry(() => import("./http.js"), "http", "HTTP status & MIME reference", "Network & web",
    "Look up what an HTTP status code means (and which redirect to use), or find the MIME type for a file extension.",
    "status code 404 301 302 redirect mime content-type extension", false),
  entry(() => import("./subnet.js"), "subnet", "Subnet calculator", "Network & web",
    "Work out the network, broadcast, host range and mask for an IPv4 or IPv6 CIDR block, or turn an address range into the smallest list of CIDR blocks.",
    "cidr ip address ipv4 ipv6 netmask range network broadcast", false),
  entry(() => import("./basicauth.js"), "basicauth", "Basic auth header", "Network & web",
    "Build an HTTP Basic Authorization header from a user name and password, or decode one. Basic auth is Base64, not encryption: only use it over HTTPS.",
    "authorization http basic username password base64 curl", false),
  entry(() => import("./checker.js"), "checker", "Dead-link checker", "Admin",
    "Probe every short link's destination from the server and list the ones that no longer work. Redirects are followed; internal addresses are refused.",
    "broken links 404 health check audit", true),
  entry(() => import("./import.js"), "import", "Import links", "Admin",
    "Load links from a CSV or JSON export (for example from another shortener). Map your column names, try a dry run first, and failed rows are listed with the reason.",
    "csv json migrate bitly yourls kutt shlink bulk", true),
  entry(() => import("./export.js"), "export", "Export links", "Admin",
    "Download every link as JSON or CSV. Passwords are never exported. For a complete backup including click history, use Maintenance.",
    "download csv json backup migrate", true),
  entry(() => import("./maintenance.js"), "maintenance", "Maintenance", "Admin",
    "Server status, removing expired links, and downloading a full database backup.",
    "backup purge expired stats overview database status", true),
];
